spring:
  application:
    name: BaseProject
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
#  cache:
#    type: redis
#  data:
#    redis:
#      host: ${REDIS_HOST}
#      port: ${REDIS_PORT}
#      password: ${REDIS_PASSWORD}

server:
  port: ${SERVER_PORT:8080}

app:
  jwt:
    secret: ${JWT_SECRET_KEY}
    expiration-ms: ${JWT_EXPIRATION_MS}
    refresh-token:
      expiration-ms: ${JWT_REFRESH_EXPIRATION_MS}